Repository adobe/xdm, pull requests merged in 2018-05, with the labels that each got.

#254 Issue#251 rename metric metric definition
  CHANGELOG.md
  package.json
  schemas/data/abandons.schema.json
  schemas/data/bounces.schema.json
  schemas/data/checkouts.schema.json
  schemas/data/clicks.schema.json
  schemas/data/impressions.schema.json
  schemas/data/link-clicks.schema.json
  schemas/data/metric.description.md
  schemas/data/metricdefinition.description.md
  schemas/data/metricdefinition.example.1.json
  schemas/data/metricdefinition.schema.json
  schemas/data/mirror-pages.schema.json
  schemas/data/non-deliverables.schema.json
  schemas/data/not-sent.schema.json
  schemas/data/opens.schema.json
  schemas/data/page-views.schema.json
  schemas/data/product-list-adds.schema.json
  schemas/data/product-list-opens.schema.json
  schemas/data/product-list-removals.schema.json
  schemas/data/product-list-reopens.schema.json
  schemas/data/product-list-views.schema.json
  schemas/data/product-views.schema.json
  schemas/data/purchases.schema.json
  schemas/data/save-for-laters.schema.json
  schemas/data/sends.schema.json
  schemas/data/unsubscriptions.schema.json
  schemas/data/user-complaints.schema.json
Labels: bug

#240 Remove id from namespace
  schemas/context/enduserids.example.1.json
  schemas/context/experienceevent.example.1.json
  schemas/context/identity.example.1.json
  schemas/context/namespace.description.md
  schemas/context/namespace.schema.json
  schemas/context/profile.example.1.json
Labels: product critical

#289 Make xdm:channel a reference
  CHANGELOG.md
  schemas/context/experienceevent.example.1.json
  schemas/context/experienceevent.schema.json
Labels: breaking

#323 #322 Add GeoUnit and OrgUnit Schemas
  CHANGELOG.md
  extensions/adobe/experience/campaign/orchestration/reportingevent.example.1.json
  extensions/adobe/experience/campaign/orchestration/reportingevent.schema.json
  package.json
  schemas/common/geounit.example.1.json
  schemas/common/geounit.schema.json
  schemas/common/orgunit.example.1.json
  schemas/common/orgunit.schema.json
  schemas/context/profile.example.1.json
  schemas/context/profile.schema.json
Labels: breaking
